site_name: Straight to the Money 💰
site_author: Carlo 'carlovo' van Overbeek

repo_url: https://github.com/Carlovo/straight_to_the_money/
edit_uri: blob/main/docs/

theme:
  name: mkdocs
  color_mode: auto
  user_color_mode_toggle: true
  locale: en

nav:
  - Home: index.md
  - Walkthrough: walkthrough.md
  - About: about.md

copyright: Copyright &copy; 2024 <a href="https://github.com/Carlovo">Carlo 'carlovo' van Overbeek</a>
